obstacle_range: 4.0
raytrace_range: 7.0
footprint: [[-0.31, -0.25], [-0.31, 0.25], [0.31, 0.25], [0.31, -0.25]]
transform_tolerance: 0.5

observation_sources: scan
scan:
  data_type: LaserScan
  topic: /ebot/laser/scan
  marking: true
  clearing: true

map_type: costmap

