global_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  update_frequency: 1.5 #before: 5.0
  publish_frequency: 0.5 #before 0.5
  static_map: true
  inflation_radius: 1.0
  cost_scaling_factor: 2.58



