local_costmap:
  global_frame: odom
  robot_base_frame: ebot_base
  update_frequency: 1.75 #before 5.0
  publish_frequency: 2.0 #before 2.0
  static_map: true
  rolling_window: true
  width: 2.5 
  height: 2.5
  resolution: 0.025 #increase to for higher res 0.025
  inflation_radius: 1.0
  cost_scaling_factor: 2.5
