DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 1.0
  min_vel_x: -1.0

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  1.0
  min_vel_trans:  -1.0

  max_vel_theta: 0.9
  min_vel_theta: 0.2

  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_th: 2.5 

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 6.28
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.5
  vx_samples: 16
  vy_samples: 0
  vth_samples: 16
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 50.0
  goal_distance_bias: 5.0
  occdist_scale: 0.01
  forward_point_distance: 0.0
  stop_time_buffer: 0.2
  scaling_speed: 0.35
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : false
  publish_cost_grid_pc: false

